### ISSUE TITLE
Angle bracket nested components syntax

### ISSUE THREAD

**Issue by Exelord** [rwjblue/ember-holy-futuristic-template-namespacing-batman#166]
Will this addon syntax still work taking into account latest `Angle bracket nested components syntax`?

**Comment by rwjblue** [comment]
Yes, there will be a migration to some other sigil since `::` has been given a different meaning upstream. In the mean time, I'd suggest not using this addon **and** attempting to use the nested invocation syntax together.

**Comment by rwjblue** [comment]
See #202 btw

**Comment by Exelord** [comment]
That's why I closed :) I saw $ coming.
