### ISSUE TITLE
Alternate Sigil Search

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-holy-futuristic-template-namespacing-batman#202]
Since [emberjs/rfcs#457](https://github.com/emberjs/rfcs/blob/master/text/0457-nested-lookups.md) repurposed the `::` sigil that this addon leverages we need to choose an alternative.

The current plan (after digging into quite a few possible alternatives) is to use `$`. See [demo AST Explorer](https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/1e757d4f4d45b1ecfbb3e467dc94fa39fe051e7e):

```hbs
<MyAddon$MyComponent::Nested />
{{my-addon$my-component/nested}}
```

The rough roll out plan will be:

- [x] Add support for both `$` and `::` #203
- [x] Release non-breaking non-deprecated version ([v0.1.8](https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/releases/tag/v0.1.8))
- [x] Create a codemod to transform from `::` to `$` (https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman-sigil-change-codemod)
- [x] Add a deprecation for using `::` https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/pull/205
- [x] Release breaking change version (0.2.x)
- [x] Release breaking change version dropping support for `::`

<details>
<summary>Discarded ideas</summary>

* `?`

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/3db6976a3c3f8497510715fbfafb67db99480b99

```hbs
<MyAddon?MyComponent::Nested />
{{my-addon?my-component/nested}}
```

* `#` - Triggers a parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/8cec1b838cd185d2dcdeccc839b2936e4da84330

```hbs
<MyAddon#MyComponent::Nested />
{{#my-addon#my-component/nested}}
```

* `->` - Triggers a parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/1e6682b28166b9fc6d4575d17e19f0d7488d5ccc

```hbs
<MyAddon->MyComponent::Nested />

{{#my-addon->my-component/nested}}
{{/my-addon->my-component/nested}}
```

* `%` - Triggers a parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/4ee700bc1e17e452c103dad29508ffbe29534ab9
```hbs
<MyAddon%MyComponent::Nested />
{{my-addon%my-component/nested}}
```

* `//` - Triggers parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/024ac709fe071b72d8166d810606b6d02416b6b0

```hbs
<MyAddon//MyComponent::Nested />
{{my-addon//my-component/nested}}
```

* `*` - Triggers parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/944f05cea327ffdb92f214e41c2dda47681e1f29

```hbs
<MyAddon*MyComponent::Nested />
{{my-addon*my-component/nested}}
```

* `+` - Triggers parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/d14849c24f84bc34f9af875f9a2e19159ffc1feb

```hbs
<MyAddon+MyComponent::Nested />
{{my-addon+my-component/nested}}
```

* `^` - Triggers parse error in curlies

https://astexplorer.net/#/gist/ac4422bc343052b89275014eafac4584/f8fc399f20aae41e06b4d4fcbce40a94fd233e15

```hbs
<MyAddon^MyComponent::Nested />
{{my-addon^my-component/nested}}
```
</details>

**Comment by pzuraq** [comment]
I agree that `$` beats out `?` here, and that having a single sigil in both curly and angle bracket syntax is best. Sad that `+` didn't work out 😩

**Comment by rwjblue** [comment]
Yeah, quite a few on the "cutting room floor" there. 😭
