### ISSUE TITLE
Engines?

### ISSUE THREAD

**Issue by amk221** [rwjblue/ember-holy-futuristic-template-namespacing-batman#265]
Hi,

Just wondering if this addon should (or does?) work with Engines, imagine the use case:

In an in-repo-addon called Styleguide:

```handlebars
{{! Demo of a component from the host app ✔}}
<MyComponent />

{{! Demo of a component from an in-repo-addon ✔}}
<InRepoAddon$MySharedComponent />

{{! Demo of a component from an in-repo engine ? }}
<InRepoEngine$MyEngineSpecificComponent />
```

(Note: This example assumes I have loaded the necessary assets using the asset loader)

**Comment by rwjblue** [comment]
Yes, each addon that authors templates with this syntax must have this addon as a dependency but other than that it works fine with engines.
